package io.nettythrift.utils;

import javax.annotation.Generated;

/**
 * 
 * @author HouKx
 * @date 2017年1月23日
 *
 */
@Generated(value = { "Generated by code, a 'trie' " })
public class HttpMethodUtil {

	public static int method(String cs) {
		return method(cs.getBytes());
	}

	public static int method(byte[] cs) {
		switch (cs[0]) {
		case 'C': {
			switch (cs[1]) {
			case 'O': {
				switch (cs[2]) {
				case 'N': {
					switch (cs[3]) {
					case 'N': {
						switch (cs[4]) {
						case 'E': {
							switch (cs[5]) {
							case 'C': {
								switch (cs[6]) {
								case 'T': {
									switch (cs[7]) {
									case ' ': {
										switch (cs[8]) {
										case '/': {
											return 9;
										}
										}
										break;
									}
									}
									break;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				case 'P': {
					switch (cs[3]) {
					case 'Y': {
						switch (cs[4]) {
						case ' ': {
							switch (cs[5]) {
							case '/': {
								return 6;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'D': {
			switch (cs[1]) {
			case 'E': {
				switch (cs[2]) {
				case 'L': {
					switch (cs[3]) {
					case 'E': {
						switch (cs[4]) {
						case 'T': {
							switch (cs[5]) {
							case 'E': {
								switch (cs[6]) {
								case ' ': {
									switch (cs[7]) {
									case '/': {
										return 8;
									}
									}
									break;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'G': {
			switch (cs[1]) {
			case 'E': {
				switch (cs[2]) {
				case 'T': {
					switch (cs[3]) {
					case ' ': {
						switch (cs[4]) {
						case '/': {
							return 5;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'H': {
			switch (cs[1]) {
			case 'E': {
				switch (cs[2]) {
				case 'A': {
					switch (cs[3]) {
					case 'D': {
						switch (cs[4]) {
						case ' ': {
							switch (cs[5]) {
							case '/': {
								return 6;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'L': {
			switch (cs[1]) {
			case 'O': {
				switch (cs[2]) {
				case 'C': {
					switch (cs[3]) {
					case 'K': {
						switch (cs[4]) {
						case ' ': {
							switch (cs[5]) {
							case '/': {
								return 6;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'M': {
			switch (cs[1]) {
			case 'K': {
				switch (cs[2]) {
				case 'C': {
					switch (cs[3]) {
					case 'O': {
						switch (cs[4]) {
						case 'L': {
							switch (cs[5]) {
							case ' ': {
								switch (cs[6]) {
								case '/': {
									return 7;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			case 'O': {
				switch (cs[2]) {
				case 'V': {
					switch (cs[3]) {
					case 'E': {
						switch (cs[4]) {
						case ' ': {
							switch (cs[5]) {
							case '/': {
								return 6;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'O': {
			switch (cs[1]) {
			case 'P': {
				switch (cs[2]) {
				case 'T': {
					switch (cs[3]) {
					case 'I': {
						switch (cs[4]) {
						case 'O': {
							switch (cs[5]) {
							case 'N': {
								switch (cs[6]) {
								case 'S': {
									switch (cs[7]) {
									case ' ': {
										switch (cs[8]) {
										case '/': {
											return 9;
										}
										}
										break;
									}
									}
									break;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'P': {
			switch (cs[1]) {
			case 'A': {
				switch (cs[2]) {
				case 'T': {
					switch (cs[3]) {
					case 'C': {
						switch (cs[4]) {
						case 'H': {
							switch (cs[5]) {
							case ' ': {
								switch (cs[6]) {
								case '/': {
									return 7;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			case 'O': {
				switch (cs[2]) {
				case 'S': {
					switch (cs[3]) {
					case 'T': {
						switch (cs[4]) {
						case ' ': {
							switch (cs[5]) {
							case '/': {
								return 6;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			case 'R': {
				switch (cs[2]) {
				case 'O': {
					switch (cs[3]) {
					case 'P': {
						switch (cs[4]) {
						case 'F': {
							switch (cs[5]) {
							case 'I': {
								switch (cs[6]) {
								case 'N': {
									switch (cs[7]) {
									case 'D': {
										switch (cs[8]) {
										case ' ': {
											switch (cs[9]) {
											case '/': {
												return 10;
											}
											}
											break;
										}
										}
										break;
									}
									}
									break;
								}
								}
								break;
							}
							}
							break;
						}
						case 'P': {
							switch (cs[5]) {
							case 'A': {
								switch (cs[6]) {
								case 'T': {
									switch (cs[7]) {
									case 'C': {
										switch (cs[8]) {
										case 'H': {
											switch (cs[9]) {
											case ' ': {
												switch (cs[10]) {
												case '/': {
													return 11;
												}
												}
												break;
											}
											}
											break;
										}
										}
										break;
									}
									}
									break;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			case 'U': {
				switch (cs[2]) {
				case 'T': {
					switch (cs[3]) {
					case ' ': {
						switch (cs[4]) {
						case '/': {
							return 5;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'T': {
			switch (cs[1]) {
			case 'R': {
				switch (cs[2]) {
				case 'A': {
					switch (cs[3]) {
					case 'C': {
						switch (cs[4]) {
						case 'E': {
							switch (cs[5]) {
							case ' ': {
								switch (cs[6]) {
								case '/': {
									return 7;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		case 'U': {
			switch (cs[1]) {
			case 'N': {
				switch (cs[2]) {
				case 'L': {
					switch (cs[3]) {
					case 'O': {
						switch (cs[4]) {
						case 'C': {
							switch (cs[5]) {
							case 'K': {
								switch (cs[6]) {
								case ' ': {
									switch (cs[7]) {
									case '/': {
										return 8;
									}
									}
									break;
								}
								}
								break;
							}
							}
							break;
						}
						}
						break;
					}
					}
					break;
				}
				}
				break;
			}
			}
			break;
		}
		}

		return -1;
	}
}
